### Send POST request with json body
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Notebook 2",
  "description": "Macbook Pro",
  "purchasePrice": 4000,
  "stock": 10
}